name: Federico Rivollier
description: I write about some of my journeys as a Magento developer in the ecommerce world.
meta_description: "Federico Rivollier Blog. I write about software and Magento related topics."

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://federivo.com'
google_analytics: 'UA-74097543-1'
gems: [jekyll-paginate,jekyll-gist]

# Details for the RSS feed generator
url: 'federivo.com'
author: 'Federico Rivollier'

sass:
    sass_dir: _sass
    style: :compressed

gist:
  noscript: false
