name: Federico Rivollier's Blog
description: Hi! This is my personal blog where I'll be posting software dev related stuff.
meta_description: "Federico Rivollier blog. Software Development."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://federivo.github.io'
google_analytics: 'UA-74097543-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'federivo.github.io'
author:         'Federico Rivollier'
